@startuml
note top of カード : ジョーカーを除く
カードコレクション o-- カード

enum ランク
カード --* ランク

enum 絵柄
カード --* 絵柄

note top of ゲームデッキ : ゲームに使用する52枚のカード
カードコレクション <|-- ゲームデッキ

note top of プレイヤーハンド : ゲームデッキから引いた5枚のカード
カードコレクション <|-- プレイヤーハンド

enum ハンド
ハンド -- プレイヤーハンド評価
プレイヤーハンド -- プレイヤーハンド評価

interface ハンド仕様
ハンド仕様 <.. プレイヤーハンド評価
ハンド仕様 <|.. ストレートフラッシュハンド仕様
ハンド仕様 <|.. フォーカードハンド仕様
ハンド仕様 <|.. フルハウスハンド仕様
ハンド仕様 <|.. フラッシュハンド仕様
ハンド仕様 <|.. ストレートハンド仕様
ハンド仕様 <|.. スリーカードハンド仕様
ハンド仕様 <|.. ツーペアハンド仕様
ハンド仕様 <|.. ワンペアハンド仕様

interface パターン仕様
パターン仕様 <|.. 全て同じ絵柄パターン仕様
パターン仕様 <|.. 連続したランクパターン仕様

全て同じ絵柄パターン仕様 <.. ストレートフラッシュハンド仕様
全て同じ絵柄パターン仕様 <.. フラッシュハンド仕様
全て同じ絵柄パターン仕様 <.. ストレートハンド仕様

連続したランクパターン仕様 <.. ストレートフラッシュハンド仕様
連続したランクパターン仕様 <.. フラッシュハンド仕様
連続したランクパターン仕様 <.. ストレートハンド仕様
@enduml
